# ??????
server.port=909

# ??? ??????????
spring.application.name=stats-server

# ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-stats
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ???????????
logging.level.ru.practicum=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Actuator (??????????? ?? ??)
management.endpoints.web.exposure.include=health,info,metrics