-- Создание таблицы locations
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    address VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Индекс для поиска по координатам
CREATE INDEX IF NOT EXISTS idx_locations_coordinates ON locations(lat, lon);

-- Индекс для поиска по имени
CREATE INDEX IF NOT EXISTS idx_locations_name ON locations(name);